databases:
  - name: post
    databaseName: post_aa30
    user: post_aa30_user
    host: dpg-clgglbt8td7s73bhldtg-a

services:
  - type: web
    name: Budget app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: post
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false